spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${properties.datasource.path}/monitoring
    username: ${properties.datasource.username}
    password: ${properties.datasource.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

spring.batch.job.names: ${job.name:NONE}