version: "3.8"
services:
  test:
    container_name: test
    image: python:3.11
    restart: unless-stopped
    volumes:
      - ./test:/code:ro
    working_dir: /code
    entrypoint: /code/entrypoint.sh
    ports:
      - 8000:8000
