version: "3.8"

volumes:
  talaria.d:
  nginx_pid:

secrets:
  nginx.fullchain:
    file: ./setup/certbot/conf/live/${DATA_PLANE_DOMAIN}/fullchain.pem
  nginx.privkey:
    file: ./setup/certbot/conf/live/${DATA_PLANE_DOMAIN}/privkey.pem

services:
  configurator:
    container_name: configurator
    image: python:${PYTHON_VERSION}
    environment:
      MODE: test
      CONTROL_PLANE_DOMAIN: ${CONTROL_PLANE_DOMAIN}
      DESCRIBING_SERVICE_URI: ${DESCRIBING_SERVICE_URI}
      DATA_PLANE_DOMAIN: ${DATA_PLANE_DOMAIN}
    restart: unless-stopped
    volumes:
      - ./configurator:/code:ro
      - ./nginx/api_gateway.conf:/nginx/api_gateway.conf
      - talaria.d:/nginx/talaria.d
    working_dir: /code
    entrypoint: /code/entrypoint.sh
    depends_on:
      - nginx
    pid: "container:nginx"
    ports:
      - "${CONFIGURATOR_PORT}:${CONFIGURATOR_PORT}"

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - talaria.d:/etc/nginx/talaria.d
      - ./nginx/log/:/var/log/nginx
    secrets:
      - source: nginx.fullchain
        target: /usr/share/nginx/certs/fullchain.pem
      - source: nginx.privkey
        target: /usr/share/nginx/certs/privkey.pem
    ports:
      - 80:80
      - 443:443
