version: "3.5"

networks:
  default:
    name: data-plane
    external: false

volumes:
  nginx-config:

services:
  gw-server:
    container_name: gw-server
    image: talaria/gw-server
    build:
      context: ./gw-server
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    restart: unless-stopped
    volumes:
      - nginx-config:/usr/share/nginx
    ports:
      - "${GW_SERVER_PORT}:${GW_SERVER_PORT}"
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx-config:/etc/nginx
      - ./setup/certbot/conf:/etc/nginx/ssl
      - ./setup/certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
