version: "3.5"

networks:
  default:
    name: data-plane
    external: false

volumes:
  talaria_conf.d:

secrets:
  nginx.fullchain:
    file: ./setup/certbot/conf/live/${DOMAIN}/fullchain.pem
  nginx.privkey:
    file: ./setup/certbot/conf/live/${DOMAIN}/privkey.pem

services:
  gw-server:
    container_name: gw-server
    image: talaria/gw-server
    build:
      context: ./gw-server
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - talaria_conf.d:/code/nginx
    ports:
      - "${GW_SERVER_PORT}:${GW_SERVER_PORT}"
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx/talaria_conf.d:/etc/nginx/talaria_conf.d
    secrets:
      - source: nginx.fullchain
        target: /usr/share/nginx/certs/fullchain.pem
      - source: nginx.privkey
        target: /usr/share/nginx/certs/privkey.pem
    ports:
      - 80:80
      - 443:443
